name: Cleanup Branches

on:
  push:
    branches:
      - master

jobs:
  cleanup-merged-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Delete merged branches
        run: |
          # Fetch all branches
          git fetch --prune
          # Loop through merged PR branches and delete
          for branch in $(git log --merges --oneline master | grep -E 'Merge pull request' | awk -F'from ' '{print $2}' | sed 's|^[^/]*/||'); do
            echo "Deleting branch: $branch"
            git branch -d "$branch" 2>/dev/null || git branch -D "$branch" || echo "Branch $branch does not exist locally."
            git push origin --delete "$branch" || echo "Branch $branch does not exist remotely."
          done

