name: Print Merged Branches

on:
  push:
    branches:
      - master # Run the action when code is pushed to master

jobs:
  list-merged-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print merged branches
        run: |
          # Fetch all branches
          git fetch --prune

          # Loop through merged PR branches and print their names
          echo "Merged PR branches:"
          for branch in $(git log --merges --oneline master | grep -E 'Merge pull request' | awk -F'from ' '{print $2}' | sed 's|^[^/]*/||'); do
            echo "$branch"
          done
