name: Delete Merged Branches

on:
  push:
    branches:
      - master  # Runs when code is pushed to the master branch

jobs:
  delete-merged-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to ensure all merged PRs are included

      - name: Delete merged branches (excluding the last one)
        run: |
          # Fetch all branches to ensure the local reference is up to date
          git fetch --prune

          # Get all merged PR branches except the most recent one
          echo "Deleting merged PR branches (excluding the last one):"
          
          # List all merged branches and exclude the most recent one
          branches=$(git log --merges --oneline master | grep -E 'Merge pull request' | awk -F'from ' '{print $2}' | sed 's|^[^/]*/||')

          # Skip the first branch in the list (which is the most recent merge)
          branches_to_delete=$(echo "$branches" | tail -n +2)

          # Loop through and delete the branches
          for branch in $branches_to_delete; do
            echo "Deleting branch: $branch"
            # Delete the local branch
            git branch -d "$branch" 2>/dev/null || git branch -D "$branch"
            # Delete the remote branch
            git push origin --delete "$branch" || echo "Branch $branch does not exist remotely."
          done
