name: Print Merged Branches

on:
  push:
    branches:
      - master  # Runs when code is pushed to the master branch

jobs:
  list-merged-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to ensure all merged PRs are included

      - name: Print merged branches (excluding the last one)
        run: |
          # Fetch all branches to ensure the local reference is up to date
          git fetch --prune

          # Get merged PR branches (excluding the most recent merge)
          echo "Merged PR branches (excluding the last one):"
          branches=$(git log --merges --oneline master | grep -E 'Merge pull request' | awk -F'from ' '{print $2}' | sed 's|^[^/]*/||')
          # Skip the last merged branch (head)
          branches_to_print=$(echo "$branches" | head -n -1)
          
          # Print the branches
          echo "$branches_to_print"
