name: Print Merged Branches

on:
  push:
    branches:
      - master  # Runs when code is pushed to the master branch

jobs:
  list-merged-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to ensure all merged PRs are included

      - name: Print merged branches (excluding the last one)
        run: |
          # Fetch all branches to ensure the local reference is up to date
          git fetch --prune

          # Get all merged PR branches except the most recent one
          echo "Merged PR branches (excluding the last one):"
          
          # List all merged branches and exclude the most recent one
          branches=$(git log --merges --oneline master | grep -E 'Merge pull request' | awk -F'from ' '{print $2}' | sed 's|^[^/]*/||')

          # Skip the first branch in the list (which is the most recent merge)
          branches_to_print=$(echo "$branches" | tail -n +2)

          # Print the remaining branches
          echo "$branches_to_print"
