name: Merge to UAT

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: write  # This allows the workflow to push to the repository
  pull-requests: write # Allows the workflow to manage PRs

jobs:
  merge-to-uat:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git user info
        run: |
          git config --global user.name "roni07"
          git config --global user.email "mdmehedihasanroni28@gmail.com"

      - name: Fetch latest changes from remote
        run: git fetch origin

      - name: Merge develop into uat with ours strategy
        run: |
          git checkout uat
          git merge origin/develop --allow-unrelated-histories -X ours

      - name: Push changes to uat branch
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/roni07/github-actions.git uat
